### ISSUE TITLE
Pymakr not compatible with Atom above 1.27.2

### ISSUE THREAD

**Issue by darox** [pycom/Pymakr#17]
If I start Pymakr with a Atom version above 1.27.2, I get an error that it's not compatible. Please fix!

**Comment by RalphHogenbirk** [comment]
Hey Darox, you're on the wrong repo, this is the old pymakr desktop app. But the latest release of the atom plugin (v1.3.3) actually has support for atom 1.27.2 so it should install.
I do see that atom released 1.28 yesterday, which is not supported yet by pymakr. Likely you are on that version. We'll release support for it as soon as possible

**Comment by adam-codeberg** [comment]
> has support for atom 1.27.2

Ok, however current release of atom is 1.40.1
