### ISSUE TITLE
Pymakr serial port module not loading anymore after upgrade of Visual Studio 1.4

### ISSUE THREAD

**Issue by kula4** [pycom/Pymakr#20]
After automatic update of Visual Studio code to 1.4 version .  I constantly get error's loading pymakr serial port module.  I worked for months without issues.  Uninstalling and reinstalling the extension did not help.  Trying to access pymakr global settings ctrl shift G gives pymakr.globalsettings not found..  Version pymakr 1.1.4
![image](https://user-images.githubusercontent.com/57617743/68573564-43deb480-0468-11ea-9572-5c27700cb4bd.png)

**Comment by pedroknup** [comment]
We are working on that. Until we release fix for Windows, I suggest you to downgrade your VSCode to 1.39 or switch temporarily to Atom.

**Comment by pedroknup** [comment]
We are working on that. Until we release fix for Windows, I suggest you downgrade your VSCode to 1.39 or switch temporarily to Atom.

**Comment by pedroknup** [comment]
We are working on that. Until we release a fix for Windows, I suggest you downgrade your VSCode to 1.39 or switch temporarily to Atom.

**Comment by pedroknup** [comment]
A new version was released few days ago with the fix for that. Please update your Pymakr vscode to 1.1.5
