### ISSUE TITLE
Pymakr commands not working with VS Code

### ISSUE THREAD

**Issue by rdlaner** [pycom/Pymakr#32]
I'm currently running:
VS Code version 1.69.0.
PyMakr extension version 2.12.3

I noticed that most of the Pymakr commands in the command palette no longer have the "PyMakr:" prefix:
<img width="614" alt="Screen Shot 2022-07-03 at 12 09 17 PM" src="https://user-images.githubusercontent.com/17415937/177053963-a335d00b-0cb8-43fb-ad84-bf0cba0ff2ec.png">
<img width="618" alt="Screen Shot 2022-07-03 at 12 09 48 PM" src="https://user-images.githubusercontent.com/17415937/177053967-0c6eff76-5f2f-4653-800c-b2fb0e6f7e49.png">

Whenever I attempt to run any of the commands that now are missing the "PyMakr:" prefix, I see this error in the PyMakr log:
```
error: PyMakr (335384) > command > Failed to run command: disconnect with params: 
error: PyMakr (335384) > command > Cannot destructure property 'device' of 'undefined' as it is undefined.
error: PyMakr (341992) > command > Failed to run command: connect with params: 
error: PyMakr (341992) > command > Cannot destructure property 'device' of 'undefined' as it is undefined.
error: PyMakr (358711) > command > Failed to run command: uploadPrompt with params: 
error: PyMakr (358711) > command > projectRef did not match an accepted type
```

Any time I try to add a new device, nothing happens. I'm out of ideas on how to get this extension to work again, please help!

**Comment by jakobrosenberg** [comment]
@rdlaner I think this has been fixed in the upcoming version. You can try it out [here](https://marketplace.visualstudio.com/items?itemName=pycom.pymakr-preview).

There's a dedicated repo for the VSC plugin. The readme should help you get started with Pymakr 2.
https://github.com/pycom/pymakr-vsc

**Comment by rdlaner** [comment]
Thanks @jakobrosenberg! Using the "Pymakr - Preview" version has resolved all my isues.
